# This is a basic workflow to help you get started with Actions

name: Build the game on Windows and Linux

# Controls when the workflow will run
on:
    push:
      tags:
        - "*"

permissions:
    contents: write
    id-token: write

jobs:
    build_linux:
        runs-on: ubuntu-latest

        steps:
            - name: Check-out repository
              uses: actions/checkout@v3
              with:
                fetch-depth: 0
            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'
                architecture: 'x64'
                cache: 'pip'
                cache-dependency-path: |
                  **/requirements*.txt
            - name: Install dependencies
              run: |
                pip install -r requirements.txt -r requirements-dev.txt
                sudo apt-get -y install libsdl2-dev
                sudo apt-get -y install patchelf
            - name: Build Executable
              run: |
                scripts/build.sh
            - name: Create Release
              uses: ncipollo/release-action@v1
              with:
                artifacts: "./dist/*"
                allowUpdates: true

    build_windows:
        runs-on: windows-latest

        steps:
            - name: Check-out repository
              uses: actions/checkout@v3
              with:
                fetch-depth: 0
            - name: Setup Windows SDK
              uses: GuillaumeFalourd/setup-windows10-sdk-action@v1.11
            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'
                architecture: 'x64'
                cache: 'pip'
                cache-dependency-path: |
                  **/requirements*.txt
            - name: Install dependencies
              run: |
                pip install -r requirements.txt -r requirements-dev.txt
            - name: Build Executable
              run: |
                scripts\build.ps1
            - name: Create Release
              uses: ncipollo/release-action@v1
              with:
                artifacts: "./dist/*"
                allowUpdates: true